"""Data models for technical indicators"""
from enum import Enum
from dataclasses import dataclass, asdict
from typing import Dict, Any, Optional
import pandas as pd


class SignalType(Enum):
    """Signal type from indicator"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    STRONG_BUY = "STRONG_BUY"
    STRONG_SELL = "STRONG_SELL"


@dataclass
class IndicatorResult:
    """Result of a single indicator calculation"""
    name: str  # 'rsi', 'macd', 'sma_20', etc.
    value: float  # Current indicator value
    signal: SignalType  # Signal generated by indicator
    timestamp: pd.Timestamp  # When calculated
    metadata: Dict[str, Any] = None  # Extra data (histogram, signal_line, etc.)
    
    def to_dict(self):
        """Convert to dictionary"""
        return {
            'name': self.name,
            'value': self.value,
            'signal': self.signal.value,
            'timestamp': self.timestamp.isoformat(),
            'metadata': self.metadata or {}
        }


@dataclass
class IndicatorsSnapshot:
    """All indicators calculated for a symbol at a timestamp"""
    symbol: str
    timestamp: pd.Timestamp
    indicators: Dict[str, IndicatorResult]  # {'rsi': IndicatorResult(...), ...}
    current_price: Optional[float] = None  # Add current price for convenience
    
    def get_all_signals(self) -> Dict[str, SignalType]:
        """Get all indicator signals"""
        return {k: v.signal for k, v in self.indicators.items()}
    
    def get(self, key: str, default: Any = None) -> Any:
        """
        Get indicator value by name (e.g., 'rsi') or other metadata.
        Returns the numeric value from IndicatorResult, or the default if not found.
        """
        if key == "close":
            return self.current_price if self.current_price is not None else default
        if key in ("symbol", "timestamp"):
            return getattr(self, key, default)
        if key in self.indicators:
            return self.indicators[key].value
        return default
    
    def to_dict(self):
        """Convert to dictionary"""
        return {
            'symbol': self.symbol,
            'timestamp': self.timestamp.isoformat(),
            'indicators': {k: v.to_dict() for k, v in self.indicators.items()},
            'signals': {k: v.value for k, v in self.get_all_signals().items()},
            'current_price': self.current_price
        }
