import abc
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

@dataclass
class AgentReport:
    """
    A structured report generated by an agent.
    """
    agent_id: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    status: str # e.g., "success", "failure", "info", "opportunity"
    message: str
    payload: Optional[Dict[str, Any]] = None # Detailed data specific to the report

class Agent(abc.ABC):
    """
    Base abstract class for all autonomous agents in the trading system.
    Defines the common interface and properties for an agent.
    """
    @property
    @abc.abstractmethod
    def agent_id(self) -> str:
        """A unique identifier for the agent."""
        pass

    @property
    @abc.abstractmethod
    def goal(self) -> str:
        """The primary objective of the agent."""
        pass

    @property
    def description(self) -> str:
        """A brief description of the agent's function."""
        return self.goal # Default to goal if not overridden

    @abc.abstractmethod
    async def run(self, *args, **kwargs) -> Optional[AgentReport]:
        """
        Executes the agent's primary logic.
        Should return an AgentReport if there's something to report.
        """
        pass

    async def initialize(self) -> None:
        """
        Initializes the agent (e.g., loading config, connecting to services).
        This method can be overridden by subclasses.
        """
        pass

    async def shutdown(self) -> None:
        """
        Shuts down the agent gracefully.
        This method can be overridden by subclasses.
        """
        pass
