import logging\nimport asyncio\nfrom datetime import datetime, timedelta\nfrom typing import Dict, Any, Callable, Awaitable\n\nfrom finance_service.agents.agent_interface import Agent, AgentReport\nfrom finance_service.core.events import Event, Events, get_event_bus\n\nlogger = logging.getLogger(__name__)\n\nclass SchedulerAgent(Agent):\n    \"\"\"Scheduler Agent - Manages and executes scheduled tasks.\"\"\"\n\n    @property\n    def agent_id(self) -> str:\n        return \"scheduler_agent\"\n\n    @property\n    def goal(self) -> str:\n        return \"Automate the execution of periodic tasks, such as market scanning, data fetching, and report generation.\"\n\n    def __init__(self, config: Dict[str, Any]):\n        self.config = config\n        self.event_bus = get_event_bus()\n        self.scheduled_tasks: Dict[str, asyncio.Task] = {}\n        logger.info(f\"SchedulerAgent initialized with config: {self.config}\")\n\n    async def run(self) -> Optional[AgentReport]:\n        \"\"\"Starts the scheduler, running predefined tasks.\"\"\"\n        logger.info(\"SchedulerAgent starting...\")\n        try:\n            # Example: Schedule a daily market scan event\n            # In a real scenario, task definitions would come from config\n            self._schedule_task(
                "daily_market_scan",
                self._trigger_daily_market_scan,
                timedelta(minutes=1) # For testing, run every minute
            )
            # Example: Schedule an hourly data refresh event\n            self._schedule_task(
                "hourly_data_refresh",
                self._trigger_hourly_data_refresh,
                timedelta(minutes=5) # For testing, run every 5 minutes
            )
\n            logger.info(\"SchedulerAgent tasks initiated.\")\n            return AgentReport(agent_id=self.agent_id, status=\"success\", message=\"SchedulerAgent started.\")\n        except Exception as e:\n            logger.error(f\"Error starting SchedulerAgent: {e}\")\n            return AgentReport(agent_id=self.agent_id, status=\"error\", message=f\"Failed to start SchedulerAgent: {e}\")\n\n    async def _schedule_task(self, task_name: str, coro: Callable[..., Awaitable[None]], interval: timedelta):\n        \"\"\"Schedules an async coroutine to run at a fixed interval.\"\"\"\n        async def task_wrapper():\n            while True:\n                try:\n                    logger.info(f\"Executing scheduled task: {task_name}\")\n                    await coro()\n                except Exception as e:\n                    logger.error(f\"Error in scheduled task {task_name}: {e}\", exc_info=True)\n                await asyncio.sleep(interval.total_seconds())\n        
        # Cancel existing task if it exists\n        if task_name in self.scheduled_tasks and not self.scheduled_tasks[task_name].done():\n            self.scheduled_tasks[task_name].cancel()\n\n        self.scheduled_tasks[task_name] = asyncio.create_task(task_wrapper())\n        logger.info(f\"Task {task_name} scheduled to run every {interval}.\")\n\n    async def _trigger_daily_market_scan(self):\n        # Publish an event that the MainOrchestratorAgent (or MarketScannerAgent) will listen to\n        await self.event_bus.publish(Event(event_type=Events.MARKET_SCAN_TRIGGER, data={\"interval\": \"daily\"}))\n        logger.info(\"Published MARKET_SCAN_TRIGGER event (daily).\")\n\n    async def _trigger_hourly_data_refresh(self):\n        # Publish an event to refresh data, which DataAgent might pick up\n        await self.event_bus.publish(Event(event_type=Events.DATA_REFRESH_TRIGGER, data={\"interval\": \"hourly\"}))\n        logger.info(\"Published DATA_REFRESH_TRIGGER event (hourly).\")\n\n    async def stop(self):\n        \"\"\"Stops all scheduled tasks.\"\"\"\n        for task_name, task in self.scheduled_tasks.items():\n            if not task.done():\n                task.cancel()\n                logger.info(f\"Cancelled scheduled task: {task_name}\")\n        await asyncio.gather(*[t for t in self.scheduled_tasks.values() if not t.done()], return_exceptions=True)\n        self.scheduled_tasks.clear()\n        logger.info(\"SchedulerAgent stopped all tasks.\")\n\n    def __repr__(self) -> str:\n        return f\"<SchedulerAgent(id=\'{self.agent_id}\')>\"\n